name: recebiapp
description: "Aplicativo para gerenciar pagamentos."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  dio: ^5.9.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  logging: ^1.3.0
  get_it: ^9.2.0
  provider: ^6.1.5+1
  flutter_stripe: ^12.1.1
  currency_text_input_formatter: ^2.3.0
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
